
server:
  port: 9010

spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: panda
    password: panda
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.playdata.panda.domain, com.playdata.panda.dto
